### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by CameronCT** [serrexlabs/react-confirm-box#4]
I'm currently using react-confirm-box with Next which is likely why this issue is occurring.

![image](https://user-images.githubusercontent.com/11495748/147728969-5928ef8f-bcd7-480a-82af-c42b5ca7df27.png)

**Comment by sanathks** [comment]
@CameronCT thanks for reporting the issue. 
 I'm checking this

**Comment by CameronCT** [comment]
I did try using `if (typeof window !== 'undefined')` prior to using any of the confirmation code however it still threw the error. Don't know if that helps, but figured I'd throw it out there.

Original example 
```js
const onClick = async () => {
   const result = await confirm("Are you sure?", options);
   if (result) {
     console.log("You click yes!");
     return;
   }
   console.log("You click No!");
 };
 ```
 
 My variation for testing
 ```js
 const onClick = async () => {
   if (typeof window !== 'undefined') {
      const result = await confirm("Are you sure?", options);
      if (result) {
        console.log("You click yes!");
        return;
      }
      console.log("You click No!");
   }
 };
 ```

**Comment by RazaShehryar** [comment]
any solution to this?

**Comment by AhmedElywa** [comment]
the issue coming from the import package at the server side the fix is import only when you use it 


```js
const onClick = async () => {
   const { confirm } = await import('react-confirm-box');
   const result = await confirm("Are you sure?", options);
   if (result) {
     console.log("You click yes!");
     return;
   }
   console.log("You click No!");
 };
```

**Comment by sanathks** [comment]
@AhmedElywa, thanks for sharing your solution.

I also think dynamic loading is the best solution for this since this module depends on the browser API 

 Maybe you can use the next/dynamic import module.
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
